# Generated by Django 4.2 on 2023-07-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_user_role_role_id_alter_user_role_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_activ",
            field=models.BooleanField(default=False),
        ),
    ]
